### ISSUE TITLE
Poor droplist colors on Linux

### ISSUE THREAD

**Issue by AndKe** [slic3r/Slic3r#4373] opened 2018-04-09 15:19 UTC
### Version
1.3.0 DEV

### Operating system type + version
Ubuntu 17.10 , Gnome

### Behavior
attaching photo of the droplist (it is hard to screenshot it.)
Same goes for all droplists (infill etc..)

![20180409_171553](https://user-images.githubusercontent.com/1468842/38506444-3222f4f8-3c1a-11e8-961d-998003074497.jpg)

**Comment by lordofhyphens** [comment] 2018-04-09 17:38
Well that's cute. Must be some weird interaction between your theme, Gnome, and wxwidgets.

I know my XFCE dark theme works fine (and normal light themes).

**Comment by AndKe** [comment] 2018-04-09 17:50
I am using stock Ubuntu theme, no modifications.

**Comment by foreachthing** [comment] 2018-04-09 20:15
I have the same thing. First I thought it was because of VirtualBox... but, yeah! Fresh build of Ubuntu 17.1 does that.
![image](https://user-images.githubusercontent.com/10420187/38520492-466d1b7c-3c43-11e8-83bd-b3ce9983693d.png)

**Comment by lordofhyphens** [comment] 2018-04-10 23:49
Yeah, I have no idea what is going on here. Can you check with the AppImage build?

**Comment by foreachthing** [comment] 2018-04-11 08:07
AppImage won't run (yet).
![image](https://user-images.githubusercontent.com/10420187/38604279-22f11166-3d70-11e8-870c-b68e6374b9f2.png)
So, I need to sort that out first...

**Comment by bubnikv** [comment] 2018-04-11 08:38
We have that as well.

Likely the problem is, that the menu is partially using the active GTK palette, and partially the colors forced by Slic3r onto the panel background.

We are looking into it.

**Comment by bubnikv** [comment] 2018-04-12 20:46
In Ubuntu 17.10 they seemingly messed up themes for GTK2. 
You may try to install the gtk2.0-examples package and run /usr/bin/gtk-demo. Indeed, the "Combo boxes" test shows the same behavior: gray on gray text. So this is an issue specific to GTK2 on Ubuntu 17.10. 

The same "gray on gray" combo boxes are shown by the popular printed board design tool "kicad" on the same system. kicad is written using wxWidgets over GTK2.

Now only if I knew where to complain.

**Comment by bubnikv** [comment] 2018-04-12 20:56
https://bugs.launchpad.net/ubuntu/artful/+source/ubuntu-themes/+bug/1725921

**Comment by bubnikv** [comment] 2018-04-12 21:20
Taking an advice from https://bugs.launchpad.net/ubuntu/artful/+source/ubuntu-themes/+bug/1725921

Edit /usr/share/themes/Ambiance/gtk-2.0/gtkrc
comment out the following line:
widget "*.gtk-combobox-popup-menu.*" style "menuitem_text_is_fg_color_workaround"

Now the combo boxes are shown correctly.

**Comment by lordofhyphens** [comment] 2018-04-13 13:06
Nothing else we can do about it. Closing.

**Closed by lordofhyphens** 2018-04-13 13:06 UTC
Labels: OS: Ubuntu 64-bit, Upstream issue, Workaround
