### ISSUE TITLE
[Minor] - In Preview tab,  "1 Layer" cannot be disabled.

### ISSUE THREAD

**Issue by sylphio** [slic3r/Slic3r#4426] opened 2018-05-23 03:37 UTC
### Version
Prusa Slic3r 1.40_alpha1

Hi, minor bug.

In the preview tab, one you check "1 Layer" it cannot be disabled.
Unchecking "1 Layer" do not restore  the 2 slider to be independant againt.

Thank

**Comment by bubnikv** [comment] 2018-05-23 08:05
You should report the Prusa3D specific errors to https://github.com/prusa3d/slic3r/issues
On which platform?

**Comment by sylphio** [comment] 2018-05-23 08:07
Thank. Win64 on win10

**Comment by bubnikv** [comment] 2018-05-23 08:14
Would you please open the issue at the Prusa3D issue tracker and describe
the issue in more detail? I cannot reproduce it.

**Comment by lordofhyphens** [comment] 2018-05-23 12:03
Closing as this appears to be specific to the Prusa3d fork. @Sylphio if you can reproduce with a build from dl.slic3r.org/dev then I will reopen.

**Closed by lordofhyphens** 2018-05-23 12:03 UTC
