### ISSUE TITLE
Wrong multiple bridges merging.

### ISSUE THREAD

**Issue by diggit** [slic3r/Slic3r#3578] opened 2016-11-20 01:03 UTC
### Version
1.3.0-dev built from master branch

### Operating system type + version
Archlinux, up to date.

### Behavior
* **Problem:** Intersecting bridging areas produces path turns above gaps. (by bridging area is meat area containing all bridge paths above one hole)
* _Steps needed to reproduce the problem_
  * Slice model with holes to bridge close to each other. (Used text in screenshot.)
* _Expected Results_
  * Continuous bridges across whole holes.
* _Actual Results_
![16-11-20_01 38 32](https://cloud.githubusercontent.com/assets/512025/20459501/c2e5cb54-aec3-11e6-9f79-ac4a8cbc7403.png)

IMO, solution would be processing all intersecting bridging areas as one and not separately

[slic3r_bridge_err.zip](https://github.com/alexrj/Slic3r/files/601814/slic3r_bridge_err.zip)

**Comment by bubnikv** [comment] 2016-11-20 01:08
> IMO, solution would be processing all intersecting bridging areas as one
and not separately

I have fixed that in the Prusa3D fork exactly the way you proposed it,
although the implementation was more involved.

**Comment by Richie76** [comment] 2016-11-20 19:56
Hi,

I just came across a similar issue using the Prusa3D Fork.
Exact version: 1.30.0.25-prusa3d-release_candidate_1_3-win64

Please see the attached picture for reference:
[wrong layer]http://www.loopback.at/wp-content/uploads/2016/11/layer_problem_slic3er-1024x752.jpg)

this is the underside of a lego duplo brick - i did some 4x4 too - there slic3r tried to print into the holes first.

could you please look into this ?

rgds, richard

**Comment by bubnikv** [comment] 2016-11-20 19:59
> I just came across a similar issue using the Prusa3D Fork.
> Exact version: 1.30.0.25-prusa3d-release_candidate_1_3-win64

That is an old build. The latest official build is 1.31.5
https://github.com/prusa3d/Slic3r/releases/tag/version_1.31.5

**Comment by Richie76** [comment] 2016-11-20 20:00
ok ill download it and test it. thanks for the quick relpy

**Comment by diggit** [comment] 2016-11-20 23:15
@bubnikv cool. I am sure it was not so simple. When you solved it, why it isn't in upstream yet?

**Comment by lordofhyphens** [comment] 2016-11-21 00:46
@diggit Hi, I am the person working on that.

The changes are generally not easy to separate from everything else he's
done so there is a pile of work on me to get them packaged upstream.

Then they need to be reviewed and approved by @alexrj. We are both people
working in our spare time on this, @bubnikv has it as his job.

**Comment by bubnikv** [comment] 2016-11-21 11:49
Duplicate of https://github.com/alexrj/Slic3r/issues/3570

**Closed** 2018-08-26 14:14 UTC
Labels: Bridges
