### ISSUE TITLE
Windows snapshot download broken

### ISSUE THREAD

**Issue by adras** [slic3r/Slic3r#4501] opened 2018-07-31 12:58 UTC
### Version
Does not apply

### Operating system type + version
Windows

### Behavior
Slic3r dev build downloads not working. Size of files available for download is 0 and files have a .zip.filepart extension. See: http://dl.slic3r.org/dev/win/

Therefore, I can't download a recent snapshot :(

**Comment by lordofhyphens** [comment] 2018-07-31 13:17
Duplicate of #4499.

Snapshot should be available in an hour.

**Closed by lordofhyphens** 2018-07-31 13:17 UTC
Labels: Duplicated Issue

**Comment by scott0122** [comment] 2018-08-08 15:03
Slic3r dev build downloads still not working.

**Comment by lordofhyphens** [comment] 2018-08-08 15:06
Locking to collect reports into #4499
