### ISSUE TITLE
Slic3r can't parse the simplest of the conditional code

### ISSUE THREAD

**Issue by RuiCarneiro** [slic3r/Slic3r#4764] opened 2019-03-22 15:13 UTC
**Describe the bug**
Since Slic3r lacks the menu option, I'm trying to use conditional Gcode to set the flow rate, it simply can't parse this

**To Reproduce**
After layer change (or before layer change gcode)

    {if [layer_num] == 0} M221 S115
    {if [layer_num] == 1} M221 S100

**Desktop (please complete the following information):**
- macOS Mojave
 - 1.3.0-1302-g05a2f902

**Comment by lordofhyphens** [comment] 2019-03-22 16:34
Please note the git short hash so I have a reference point. "Latest dev" means nothing

**Comment by RuiCarneiro** [comment] 2019-03-23 05:37
> Please note the git short hash so I have a reference point. "Latest dev" means nothing

Done.

**Comment by lordofhyphens** [comment] 2019-03-24 01:55
@RuiCarneiro That's not a hash I recognize (it doesn't show up in the commit history of Slic3r at all).
Current newest build as of writing is https://dl.slic3r.org/dev/mac/slic3r-1.3.1-dev-05a2f90-osx.dmg

I just checked on 05a2f9028 and it works as expected with your provided gcode in the before layer change gcode.

I don't know what's going on.

**Comment by lordofhyphens** [comment] 2019-03-24 05:33
Since I can't reproduce on a current dev build, closing.

**Closed by lordofhyphens** 2019-03-24 05:33 UTC
Labels: Can't Reproduce - Development Build, Can't Reproduce - Official Build, Custom GCode
