### ISSUE TITLE
Gyroid Pattern seems incorrect on Linux 1.3.0 AppImage build

### ISSUE THREAD

**Issue by ML3D** [slic3r/Slic3r#4653] opened 2018-12-25 20:26 UTC
When using Slic3r 1.3.0 AppImage download for Linux...
The infill pattern does not consist of all curved lines, instead it shows about 50% straight lines.

Comparing same settings in the Windows version with Gyroid infill, all the lines are curved.

![slic3rgyroid_linux130](https://user-images.githubusercontent.com/12176262/50426332-3e707f80-0840-11e9-82f1-f7c3e7d2391d.png)

**Comment by lordofhyphens** [comment] 2018-12-30 16:36
@ML3D can you upload a zipped copy of the model and the exported config (Ctrl-E)?

**Comment by lordofhyphens** [comment] 2018-12-30 16:41
I can't reproduce with a simple rectangular prism and a fixed layer height.

![image](https://user-images.githubusercontent.com/31754/50549274-79e3c300-0c1f-11e9-9169-1644038bf109.png)

**Comment by lordofhyphens** [comment] 2018-12-31 04:47
@ML3D I should have fixed the 1.3.1 AppImages so you can try a build from https://dl.slic3r.org/dev/linux and see if it sorts it out for you.

**Comment by ML3D** [comment] 2018-12-31 18:15
Hi @lordofhyphens , thanks. I downloaded the Slic3r-master-latest.AppImage.
This actually fixed the gyroid pattern! However... now I have another glitch. When I adjust the # of top and bottom layers, they essentially disappear and I have only infill from bottom to top. Very strange. ( This happens with the Dev version download also )

**Comment by lordofhyphens** [comment] 2019-01-01 07:18
Known issue, #4620. Closing this issue.

**Closed by lordofhyphens** 2019-01-01 07:18 UTC
Labels: Can't Reproduce - Development Build, Needs more info, OS: Linux
