### ISSUE TITLE
"Brim connections width" setting causes crash

### ISSUE THREAD

**Issue by frankvdh** [slic3r/Slic3r#4674] opened 2019-01-03 20:27 UTC
**Describe the bug**
Slic3r-master-latest and Slic3r-1.3.1-dev-b766128-x86_64 crash or lockup when I load the attached STL.v1.29 works OK. After experimenting with turning various settings on/off, this seems to be associated with the "Brim connections width" setting in my configuration... when I had it set to 5mm, Slic3r crashed. When I changed it to 0mm, Slic3r worked OK.

**To Reproduce**
Add the attached STL in Slic3r. Load config.ini, The image is displayed. Then Slic3r crashes after displaying "Generating brim".

**3D Model and Slic3r Configuration Export**
Attached ZIP archive containing a copy of the 3D model you are seeing this bug with and a CTRL-E export of the configuration used.

**Expected behavior**
No crash..

**Desktop (please complete the following information):**
 - OS: Linux Ubuntu 18.10
 - Version Slic3r-master-latest and Slic3r-1.3.1-dev-b766128-x86_64
[Water_Spiral_Large.zip](https://github.com/slic3r/Slic3r/files/2725178/Water_Spiral_Large.zip)

**Comment by lordofhyphens** [comment] 2019-01-04 06:37
This seems suspicious given that I just fixed something around the solid spacing 
(which gets used by the bring) #4662.

**Comment by lordofhyphens** [comment] 2019-01-04 06:45
Can you reproduce with https://dl.slic3r.org/dev/linux/Slic3r-1.3.1-dev-39b157b-x86_64.AppImage?

Also, what is the git commit hash for that copy of Slic3r-master-latest (see about Slic3r window in the application)?

I can't find the short commit hash b766128 in the last month's worth of commits.

**Comment by frankvdh** [comment] 2019-01-04 18:10
Hi Joseph,
I just tried it with
https://dl.slic3r.org/dev/linux/Slic3r-1.3.1-dev-39b157b-x86_64.AppImage --
it doesn't crash, but I think that's because of some other issue... it
takes a **long*** time doing "Infilling layers" (many minutes, but it's
still responding to clicks). That applies whether or not I have "Brim
connections width" set to 0 or 5. I suspect it's not even getting to the
point where that used to cause a crash. Changing "Fill density" to 0% locks
it up completely.

The git commit hash for that copy of Slic3r-master-latest is 45353b7.
However, strangely it doesn't crash now. Instead, it also takes forever
doing "Infilling layers". Maybe I got it wrong that it crashed. But I don't
think so.

Frank

**Comment by lordofhyphens** [comment] 2019-01-05 04:38
@frankvdh I can't reproduce "taking forever" on your test model with that config on my system on that build of Slic3r.

**Comment by lordofhyphens** [comment] 2019-01-06 00:46
Closing. @frankvdh if you could report the "infill taking forever" separate with model + config that would be good.

**Closed by lordofhyphens** 2019-01-06 00:46 UTC
Labels: Support material

**Comment by lordofhyphens** [comment] 2019-01-06 00:47
Reported issue is duplicate of #4654
