### ISSUE TITLE
"dont support bridges" option not working

### ISSUE THREAD

**Issue by Tinchus2009** [slic3r/Slic3r#4090] opened 2017-08-19 12:25 UTC
### Version
_1.2.9-1120-g13f121e

### Operating system type + version
win10 64

### Behavior
It was fixed in previous dev versions I think, but now there seems to have rolled back? Bridges that should not be supported at all are being supported now, despite the "no support bridges " is activated or not.

![supports](https://user-images.githubusercontent.com/14299602/29486596-52fab1a0-84c0-11e7-9b06-ab3014c36eda.png)

**Comment by lordofhyphens** [comment] 2017-10-02 04:32
Gap fill isn't detected, IIRC, as a "bridge". Neither are "bridges" that are only perimeters.

**Comment by VanessaE** [comment] 2019-08-25 01:25
Duplicate of #3672

**Closed by VanessaE** 2019-08-25 01:25 UTC
Labels: Bridges, Regression, Support material
