### ISSUE TITLE
Ripples only on the toplayer

### ISSUE THREAD

**Issue by artbody** [slic3r/Slic3r#4361] opened 2018-04-03 14:20 UTC
This is the result with slic3r
![img_20180401_105018](https://user-images.githubusercontent.com/25343071/38244577-67e3371c-373b-11e8-9fbe-63a08f88a1ff.jpg)

### Version
_Version of Slic3r 1.3.0 and 1.2.9_

### Behavior
* _have a look at the Picture the ripples on the toplayer_
* _this problem doesn't exist if i use cura as slicer_
  * _**it only exists on the toplayer all other layer are ok**_

This picture is with cura slicer
![img_20180402_093712](https://user-images.githubusercontent.com/25343071/38254683-31b85202-375a-11e8-996a-4edbe1e140e3.jpg)

#### STL/Config (.ZIP) where problem occurs
_Upload a zipped copy of an STL and your config (`File -> Export Config`)_
[part.zip](https://github.com/slic3r/Slic3r/files/1871863/part.zip)

**Comment by artbody** [comment] 2018-04-03 14:25
I've done a little bit of research on the Problem above
So it looks like a Problem with the extruder and Filament flow.
The extruder runs in PULSES where it should run in a continuous way
it is NOT a problem of the printer because same part sliced with cura are printed quite smooth and are ok.

**Comment by lordofhyphens** [comment] 2018-04-03 23:33
Compare the gcode generated.

**Comment by lordofhyphens** [comment] 2018-04-05 04:11
Why are your top solid lines thinner than your nozzle? 88% is computed over *layer height*, so you're asking for lines less than half the width of your nozzle. Nothing good will come of that. Cura (I tested with Cura 3 and using the nozzle diameter from your config) defaults the top/bottom line width to 0.4.

I also don't know what you mean by running in "pulses"; gcode doesn't indicate anything is awry.

I am also generally unable to reproduce this in my own printing (when using sensible line widths). 

If you want to compare to Cura, override the top/bottom line width to 0.176 (which is about what the width you asked for in Slic3r) and see how the print works out. Or set the top fill line width to auto. 

I'm closing for now; if you can provide additional evidence then I will reopen.

**Closed by lordofhyphens** 2018-04-05 04:11 UTC
Labels: Can't Reproduce - Development Build

**Comment by artbody** [comment] 2018-04-05 07:35
> Or set the top fill line width to auto.
![shot_18-04-05_092659](https://user-images.githubusercontent.com/25343071/38352494-a95e7566-38b3-11e8-992a-d158e7c4c15a.jpg)
this are my settings

With in Pulses i mean that all layers are ok except the toplayer
while printing the toplayer the extruder  rotates (about 10 or 20 steps(half a second)) -stops(half a second) - rotates ...

**Comment by lordofhyphens** [comment] 2018-04-05 12:45
Download 1.3.0-dev from dl.slic3r.org/dev 

That picture shows an old version.

Also, you had provided the gcode export. Since Slic3r appends the used config at the end of the gcode file, I know exactly what got used to produce that gcode. That is not what you showed via screenshot.
